### ISSUE TITLE
kubectl run command output is not a valid yaml

### ISSUE THREAD

**Issue by perk-sumo** [SumoLogic/sumologic-kubernetes-tools#11]
It adds the kubectl output, eg.
```pod "tools" deleted```

**Comment by perk-sumo** [comment]
The `pod "tools" deleted` output comes from the `kubectl` command.
I don't see this output using the kubectl version 1.18.

**Comment by sumo-drosiek** [comment]
Additionaly there is:
```
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
```

**Comment by sumo-drosiek** [comment]
I propose to use `grep -v` to get rid of them

**Comment by perk-sumo** [comment]
@sumo-drosiek this is something different - it's `helm` related and not `kubectl` related - it's tracked under https://github.com/SumoLogic/sumologic-kubernetes-tools/issues/15

**Comment by perk-sumo** [comment]
This issue (`pod "tools" deleted`) can be fixed by adding the `--quiet` flag to the `kubectl run`.
It's working since kubectl version 1.14
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md#notable-features
