### ISSUE TITLE
Generated output contains extra output

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-tools#15]
Piping output to a file, the generated output contains the following at the top:

```manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
```

This prevents running kubectl apply on the yaml until removed.

**Comment by frankreno** [comment]
The following is also at the bottom of the YAML

**Comment by perk-sumo** [comment]
The `manifest_sorter.go:192: info: skipping unknown hook: "crd-install"` comes from the helm command so it's something we could fix.
The `pod "tools" deleted` comes from the `kubectl` command - I'm not sure we can do anything about it without wrapping this with custom script.

**Comment by perk-sumo** [comment]
The second issue is tracked under another task: https://github.com/SumoLogic/sumologic-kubernetes-tools/issues/11
