### ISSUE TITLE
Build ARM images

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-tools#160]
Similar to how https://github.com/SumoLogic/sumologic-kubernetes-fluentd and https://github.com/SumoLogic/sumologic-kubernetes-setup are built at the moment, ideally we want to support the following architectures:

- `linux/amd64`
- `linux/arm/v7`
- `linux/arm64/v8`

**Comment by swiatekm-sumo** [comment]
Implemented in #172
