### ISSUE TITLE
[receiver-mock] Support traces

### ISSUE THREAD

**Issue by mat-rumian** [SumoLogic/sumologic-kubernetes-tools#47]
Please add support to the traces in the **receiver-mock** :)

**Comment by swiatekm-sumo** [comment]
Once we have OTLPHTTP support for logs and metrics from #281 and #282, traces over that protocol shouldn't be too difficult to do.

**Comment by aboguszewski-sumo** [comment]
I think that this is done (as of versions `>=v2.13`)

**Comment by swiatekm-sumo** [comment]
Yes, done in #324 #318 #317
